version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04"
    user: root
    ports:
      - "1434:1433"
    volumes:
      - "/var/lib/docker/volumes/mssql_db/_data:/var/opt/mssql/data"
    environment:
      SA_PASSWORD: "Secret_Password123"
      ACCEPT_EULA: "Y"

